// 豆包语音合成模型 2.0 的音色。出处是官方文档《音色列表》里「豆包语音合成模型2.0」的两张表（中文和外语），2026-10-09 读的：
// https://docs.volcengine.com/docs/6561/1257544
// 官方读音色列表的接口要用账号的 AK/SK 签名，用语音的 API Key 读不了，所以登记在这里；官方出了新音色要来这里补。
// 每一行是：音色 ID、名字、适合的场景。语言和性别写在 ID 里（zh_female_…），不另外登记。

export const DOUBAO_VOICES: [id: string, name: string, use: string][] = [
  ['zh_female_vv_uranus_bigtts', "Vivi 2.0", "通用场景"],
  ['zh_female_xiaohe_uranus_bigtts', "小何 2.0", "通用场景"],
  ['zh_male_m191_uranus_bigtts', "云舟 2.0", "通用场景"],
  ['zh_male_taocheng_uranus_bigtts', "小天 2.0", "通用场景"],
  ['zh_male_liufei_uranus_bigtts', "刘飞 2.0", "通用场景"],
  ['zh_female_sophie_uranus_bigtts', "魅力苏菲 2.0", "通用场景"],
  ['zh_female_qingxinnvsheng_uranus_bigtts', "清新女声 2.0", "通用场景"],
  ['zh_female_cancan_uranus_bigtts', "知性灿灿 2.0", "角色扮演"],
  ['zh_female_sajiaoxuemei_uranus_bigtts', "撒娇学妹 2.0", "角色扮演"],
  ['zh_female_tianmeixiaoyuan_uranus_bigtts', "甜美小源 2.0", "通用场景"],
  ['zh_female_tianmeitaozi_uranus_bigtts', "甜美桃子 2.0", "通用场景"],
  ['zh_female_shuangkuaisisi_uranus_bigtts', "爽快思思 2.0", "通用场景"],
  ['zh_female_peiqi_uranus_bigtts', "佩奇猪 2.0", "视频配音"],
  ['zh_female_linjianvhai_uranus_bigtts', "邻家女孩 2.0", "通用场景"],
  ['zh_male_shaonianzixin_uranus_bigtts', "少年梓辛 2.0", "通用场景"],
  ['zh_male_sunwukong_uranus_bigtts', "猴哥 2.0", "视频配音"],
  ['zh_female_yingyujiaoxue_uranus_bigtts', "Tina老师 2.0", "教育场景"],
  ['zh_female_kefunvsheng_uranus_bigtts', "暖阳女声 2.0", "客服场景"],
  ['zh_female_xiaoxue_uranus_bigtts', "儿童绘本 2.0", "有声阅读"],
  ['zh_male_dayi_uranus_bigtts', "大壹 2.0", "视频配音"],
  ['zh_female_mizai_uranus_bigtts', "黑猫侦探社咪仔 2.0", "视频配音"],
  ['zh_female_jitangnv_uranus_bigtts', "鸡汤女 2.0", "视频配音"],
  ['zh_female_meilinvyou_uranus_bigtts', "魅力女友 2.0", "通用场景"],
  ['zh_female_liuchangnv_uranus_bigtts', "流畅女声 2.0", "视频配音"],
  ['zh_male_ruyayichen_uranus_bigtts', "儒雅逸辰 2.0", "视频配音"],
  ['en_male_tim_uranus_bigtts', "Tim", ""],
  ['en_female_dacey_uranus_bigtts', "Dacey", ""],
  ['en_female_stokie_uranus_bigtts', "Stokie", ""],
  ['zh_female_wenroumama_uranus_bigtts', "温柔妈妈 2.0", "通用场景"],
  ['zh_male_jieshuoxiaoming_uranus_bigtts', "解说小明 2.0", "通用场景"],
  ['zh_female_tvbnv_uranus_bigtts', "TVB女声 2.0", "通用场景"],
  ['zh_male_yizhipiannan_uranus_bigtts', "译制片男 2.0", "通用场景"],
  ['zh_female_qiaopinv_uranus_bigtts', "俏皮女声 2.0", "通用场景"],
  ['zh_female_zhishuaiyingzi_uranus_bigtts', "直率英子 2.0", "角色扮演"],
  ['zh_male_linjiananhai_uranus_bigtts', "邻家男孩 2.0", "通用场景"],
  ['zh_male_silang_uranus_bigtts', "四郎 2.0", "角色扮演"],
  ['zh_male_ruyaqingnian_uranus_bigtts', "儒雅青年 2.0", "通用场景"],
  ['zh_male_qingcang_uranus_bigtts', "擎苍 2.0", "角色扮演"],
  ['zh_male_xionger_uranus_bigtts', "熊二 2.0", "角色扮演"],
  ['zh_female_yingtaowanzi_uranus_bigtts', "樱桃丸子 2.0", "角色扮演"],
  ['zh_male_wennuanahu_uranus_bigtts', "温暖阿虎 2.0", "通用场景"],
  ['zh_male_naiqimengwa_uranus_bigtts', "奶气萌娃 2.0", "通用场景"],
  ['zh_female_popo_uranus_bigtts', "婆婆 2.0", "通用场景"],
  ['zh_female_gaolengyujie_uranus_bigtts', "高冷御姐 2.0", "通用场景"],
  ['zh_male_aojiaobazong_uranus_bigtts', "傲娇霸总 2.0", "通用场景"],
  ['zh_male_lanyinmianbao_uranus_bigtts', "懒音绵宝 2.0", "角色扮演"],
  ['zh_male_fanjuanqingnian_uranus_bigtts', "反卷青年 2.0", "通用场景"],
  ['zh_female_wenroushunv_uranus_bigtts', "温柔淑女 2.0", "通用场景"],
  ['zh_female_gufengshaoyu_uranus_bigtts', "古风少御 2.0", "角色扮演"],
  ['zh_male_huolixiaoge_uranus_bigtts', "活力小哥 2.0", "通用场景"],
  ['zh_male_baqiqingshu_uranus_bigtts', "霸气青叔 2.0", "有声阅读"],
  ['zh_male_xuanyijieshuo_uranus_bigtts', "悬疑解说 2.0", "有声阅读"],
  ['zh_female_mengyatou_uranus_bigtts', "萌丫头 2.0", "通用场景"],
  ['zh_female_tiexinnvsheng_uranus_bigtts', "贴心女声 2.0", "通用场景"],
  ['zh_female_jitangmei_uranus_bigtts', "鸡汤妹妹 2.0", "通用场景"],
  ['zh_male_cixingjieshuonan_uranus_bigtts', "磁性解说男声 2.0", "通用场景"],
  ['zh_male_liangsangmengzai_uranus_bigtts', "亮嗓萌仔 2.0", "通用场景"],
  ['zh_female_kailangjiejie_uranus_bigtts', "开朗姐姐 2.0", "通用场景"],
  ['zh_male_gaolengchenwen_uranus_bigtts', "高冷沉稳 2.0", "通用场景"],
  ['zh_male_shenyeboke_uranus_bigtts', "深夜播客 2.0", "通用场景"],
  ['zh_male_lubanqihao_uranus_bigtts', "鲁班七号 2.0", "角色扮演"],
  ['zh_female_jiaochuannv_uranus_bigtts', "娇喘女声 2.0", "通用场景"],
  ['zh_female_linxiao_uranus_bigtts', "林潇 2.0", "角色扮演"],
  ['zh_female_lingling_uranus_bigtts', "玲玲姐姐 2.0", "角色扮演"],
  ['zh_female_chunribu_uranus_bigtts', "春日部姐姐 2.0", "角色扮演"],
  ['zh_male_tangseng_uranus_bigtts', "唐僧 2.0", "角色扮演"],
  ['zh_male_zhuangzhou_uranus_bigtts', "庄周 2.0", "角色扮演"],
  ['zh_male_kailangdidi_uranus_bigtts', "开朗弟弟 2.0", "通用场景"],
  ['zh_male_zhubajie_uranus_bigtts', "猪八戒 2.0", "角色扮演"],
  ['zh_female_ganmaodianyin_uranus_bigtts', "感冒电音姐姐 2.0", "角色扮演"],
  ['zh_female_chanmeinv_uranus_bigtts', "谄媚女声 2.0", "通用场景"],
  ['zh_female_nvleishen_uranus_bigtts', "女雷神 2.0", "角色扮演"],
  ['zh_female_qinqienv_uranus_bigtts', "亲切女声 2.0", "通用场景"],
  ['zh_male_kuailexiaodong_uranus_bigtts', "快乐小东 2.0", "通用场景"],
  ['zh_male_kailangxuezhang_uranus_bigtts', "开朗学长 2.0", "通用场景"],
  ['zh_male_youyoujunzi_uranus_bigtts', "悠悠君子 2.0", "通用场景"],
  ['zh_female_wenjingmaomao_uranus_bigtts', "文静毛毛 2.0", "通用场景"],
  ['zh_female_zhixingnv_uranus_bigtts', "知性女声 2.0", "通用场景"],
  ['zh_male_qingshuangnanda_uranus_bigtts', "清爽男大 2.0", "通用场景"],
  ['zh_male_yuanboxiaoshu_uranus_bigtts', "渊博小叔 2.0", "通用场景"],
  ['zh_male_yangguangqingnian_uranus_bigtts', "阳光青年 2.0", "通用场景"],
  ['zh_female_qingchezizi_uranus_bigtts', "清澈梓梓 2.0", "通用场景"],
  ['zh_female_tianmeiyueyue_uranus_bigtts', "甜美悦悦 2.0", "通用场景"],
  ['zh_female_xinlingjitang_uranus_bigtts', "心灵鸡汤 2.0", "通用场景"],
  ['zh_male_wenrouxiaoge_uranus_bigtts', "温柔小哥 2.0", "通用场景"],
  ['zh_female_roumeinvyou_uranus_bigtts', "柔美女友 2.0", "通用场景"],
  ['zh_male_dongfanghaoran_uranus_bigtts', "东方浩然 2.0", "通用场景"],
  ['zh_female_wenrouxiaoya_uranus_bigtts', "温柔小雅 2.0", "通用场景"],
  ['zh_male_tiancaitongsheng_uranus_bigtts', "天才童声 2.0", "通用场景"],
  ['zh_female_wuzetian_uranus_bigtts', "武则天 2.0", "角色扮演"],
  ['zh_female_gujie_uranus_bigtts', "顾姐 2.0", "角色扮演"],
  ['zh_male_guanggaojieshuo_uranus_bigtts', "广告解说 2.0", "通用场景"],
  ['zh_female_shaoergushi_uranus_bigtts', "少儿故事 2.0", "有声阅读"],
  ['ar_female_dina_uranus_bigtts', "Dina", "通用场景、视频配音"],
  ['ar_female_fatma_uranus_bigtts', "Fatma", ""],
  ['ar_male_youssef_uranus_bigtts', "Youssef", "通用场景、有声阅读"],
  ['de_female_bv081_uranus_bigtts', "Stella", "教学场景、客服场景"],
  ['de_male_sven_uranus_bigtts', "Sven", "通用场景、教学场景"],
  ['en_male_alberto_uranus_bigtts', "Alberto", "通用场景、教学场景"],
  ['en_male_alex_uranus_bigtts', "Alex", "通用场景、视频配音"],
  ['en_female_allison_uranus_bigtts', "Allison", "视频配音"],
  ['en_male_bill_jones_corey_uranus_bigtts', "Bill", "通用场景、视频配音"],
  ['en_male_brad_pitt_p1_uranus_bigtts', "Brad_Pitt", "通用场景、视频配音"],
  ['en_female_brittney_uranus_bigtts', "Brittney", "通用场景、视频配音"],
  ['en_female_brittney_pimintel_uranus_bigtts', "Zoe", "有声阅读、客服场景"],
  ['en_male_bruce_uranus_bigtts', "Adrian", "通用场景、视频配音"],
  ['en_male_chandler_p1_uranus_bigtts', "Leo", ""],
  ['en_male_cowboy_john_b_uranus_bigtts', "John", "角色扮演"],
  ['en_male_david_uranus_bigtts', "David", "通用场景、有声阅读"],
  ['en_male_diyuwenrounan_uranus_bigtts', "Julian", "有声阅读"],
  ['en_male_godfather_uranus_bigtts', "Godfather", "有声阅读、角色扮演"],
  ['en_male_gollum_uranus_bigtts', "Gollum", "角色扮演"],
  ['en_male_hades_uranus_bigtts', "Beau", "通用场景、视频配音"],
  ['en_female_hayley_uranus_bigtts', "Hayley", "教学场景、视频配音"],
  ['en_male_jamie_uranus_bigtts', "Jamie", "通用场景、教学场景"],
  ['en_female_jane_uranus_bigtts', "Jane", "视频配音"],
  ['en_female_jenny_uranus_bigtts', "Jenny", "通用场景、客服场景"],
  ['en_male_jidongchuanjiaoshi_uranus_bigtts', "Blaze", "角色扮演"],
  ['en_male_jimmy_uranus_bigtts', "Jimmy", "通用场景、视频配音"],
  ['en_female_joanne_uranus_bigtts', "Joanne", "通用场景、有声阅读"],
  ['en_male_joker_uranus_bigtts', "Joker", "视频配音"],
  ['en_male_josh_uranus_bigtts', "Josh", "视频配音"],
  ['en_male_josh_coery_uranus_bigtts', "Josiah", "教学场景、视频配音"],
  ['en_male_kevin_uranus_bigtts', "Kevin", "教学场景、视频配音"],
  ['en_male_knightley_uranus_bigtts', "Knightley", "有声阅读"],
  ['en_female_lana_del_rey_kelley_d_p1_uranus_bigtts', "Lynn", "角色扮演"],
  ['en_female_lana_del_rey_parky_s_p1_uranus_bigtts', "Ivy", "客服场景"],
  ['en_male_marcus_uranus_bigtts', "Marcus", "通用场景、有声阅读"],
  ['en_female_mel_uranus_bigtts', "Mel", "教学场景、客服场景"],
  ['en_male_michael_uranus_bigtts', "Hank", "通用场景、教学场景"],
  ['en_male_michael_kevin_uranus_bigtts', "Michael_Kevin", "通用场景、教学场景"],
  ['en_female_myra_uranus_bigtts', "Myra", "教学场景"],
  ['en_female_myra_cmb_uranus_bigtts', "Sunny", "教学场景、客服场景"],
  ['en_female_nadia_uranus_bigtts', "Blair", "通用场景、视频配音"],
  ['en_female_natasha_uranus_bigtts', "Natasha", "通用场景、视频配音"],
  ['en_female_rachel_p1_uranus_bigtts', "Rachel", ""],
  ['en_male_ronald_uranus_bigtts', "Ronald", "有声阅读"],
  ['en_male_russell_uranus_bigtts', "Russell", "通用场景、教学场景"],
  ['en_female_scarlet_p1_uranus_bigtts', "Scarlet", "客服场景"],
  ['en_female_sharron_uranus_bigtts', "Sharron", ""],
  ['en_male_simba_p1_uranus_bigtts', "Simba", "通用场景、视频配音"],
  ['en_female_skye_uranus_bigtts', "Skye", "通用场景"],
  ['en_male_tom_hiddleston_p1_uranus_bigtts', "Tom", "通用场景、有声阅读"],
  ['en_male_valentino_uranus_bigtts', "Valentino", "通用场景、视频配音"],
  ['en_male_valentino_corey_uranus_bigtts', "Clark", "视频配音"],
  ['en_female_wenrouzhishijieshuonv_uranus_bigtts', "Megan", "客服场景"],
  ['en_female_xinwenjieshuonv_uranus_bigtts', "Kayla", "角色扮演"],
  ['en_male_yangguangjieshuonan_uranus_bigtts', "Dylan", "通用场景、视频配音"],
  ['en_female_zendaya_p1_uranus_bigtts', "Zendaya", "教学场景、客服场景"],
  ['es_female_bv084_uranus_bigtts', "Gracie", "通用场景、客服场景"],
  ['es_male_dani_uranus_bigtts', "Dani", "有声阅读、视频配音"],
  ['es_male_guillem_uranus_bigtts', "Guillem", "有声阅读"],
  ['es_female_ht_mx_f6_uranus_bigtts', "Marisol", "通用场景、视频配音"],
  ['fr_female_fr_bv078_uranus_bigtts', "Simone", "通用场景、视频配音"],
  ['fr_female_fr_f47_uranus_bigtts', "Camille", "教学场景、客服场景"],
  ['fr_male_fr_m29_uranus_bigtts', "Maurice", "有声阅读、视频配音"],
  ['fr_male_usseau_uranus_bigtts', "Usseau", "通用场景、客服场景"],
  ['id_male_bv160_uranus_bigtts', "Rocco", "通用场景、视频配音"],
  ['id_male_bv160dialogue_uranus_bigtts', "Jude", "通用场景、视频配音"],
  ['id_male_bv160narration_uranus_bigtts', "Hugo", "有声阅读、视频配音"],
  ['id_female_bv161_uranus_bigtts', "Clara", "通用场景、视频配音"],
  ['id_female_bv161dialogue_uranus_bigtts', "Sylvia", "通用场景、视频配音"],
  ['id_female_bv161narration_uranus_bigtts', "Celeste", "通用场景、视频配音"],
  ['id_female_bv164_uranus_bigtts', "Crew", "通用场景、视频配音"],
  ['id_male_bv164dialogue_uranus_bigtts', "Elian", "视频配音"],
  ['id_male_bv164narration_uranus_bigtts', "Ronan", "有声阅读、视频配音"],
  ['id_female_f20_uranus_bigtts', "Chloe", "视频配音"],
  ['id_male_han_uranus_bigtts', "Han", "通用场景"],
  ['id_male_m08_uranus_bigtts', "Kyle", "通用场景、教学场景"],
  ['id_female_phulia_uranus_bigtts', "Phulia", "通用场景、视频配音"],
  ['ja_female_bv024_uranus_bigtts', "Bonnie", "通用场景、教学场景"],
  ['ja_female_bv520_uranus_bigtts', "Poppy", "视频配音、角色扮演"],
  ['ja_female_bv521_uranus_bigtts', "Aoi", "角色扮演"],
  ['ja_female_bv522_uranus_bigtts', "Hana", "通用场景、教学场景"],
  ['ja_female_bv523_uranus_bigtts', "Lily", "角色扮演"],
  ['ja_male_bv524_uranus_bigtts', "Ken", "通用场景、视频配音"],
  ['ja_female_minimi_uranus_bigtts', "Minimi", "通用场景、视频配音"],
  ['ja_female_shirou_uranus_bigtts', "Shirou", "视频配音、角色扮演"],
  ['ko_male_bv545_uranus_bigtts', "Jay", "通用场景、视频配音"],
  ['ko_female_bv546_uranus_bigtts', "Momo", "视频配音、角色扮演"],
  ['ko_male_m03_uranus_bigtts', "Minho", "通用场景、客服场景"],
  ['ko_male_shane_uranus_bigtts', "Shane", "有声阅读、教学场景"],
  ['ms_male_ham_uranus_bigtts', "Ham", "通用场景、教学场景"],
  ['ms_male_naim_uranus_bigtts', "Naim", "通用场景、客服场景"],
  ['mx_female_bv065_uranus_bigtts', "Irene", "教学场景、视频配音"],
  ['mx_male_bv165dialogue_uranus_bigtts', "Diego", "有声阅读、视频配音"],
  ['mx_male_bv165narrator_uranus_bigtts', "Marcos", "有声阅读、视频配音"],
  ['mx_female_bv166dialogue_uranus_bigtts', "Lucy", "通用场景、视频配音"],
  ['mx_female_bv166emotion_uranus_bigtts', "Rosa", "通用场景、视频配音"],
  ['mx_female_bv166narrator_uranus_bigtts', "Freya", "有声阅读、视频配音"],
  ['mx_male_felipe_uranus_bigtts', "Felipe", "通用场景、有声阅读"],
  ['mx_male_ht_mx_m012_uranus_bigtts', "Derek", "教学场景、视频配音"],
  ['mx_female_leslie_uranus_bigtts', "Leslie", "通用场景、客服场景"],
  ['mx_male_marcelo_uranus_bigtts', "Marcelo", "通用场景、视频配音"],
  ['pt_male_bv172_uranus_bigtts', "Sam", "通用场景、客服场景"],
  ['pt_male_bv172dialogue_uranus_bigtts', "Walter", "视频配音"],
  ['pt_male_bv172emotion_uranus_bigtts', "Vincent", "教学场景、视频配音"],
  ['pt_male_bv172narrator_uranus_bigtts', "Miles", "有声阅读、角色扮演"],
  ['pt_female_bv173_uranus_bigtts', "Diana", "通用场景、教学场景"],
  ['pt_female_bv173dialogue_uranus_bigtts', "Elena", "视频配音、客服场景"],
  ['pt_female_bv173emotion_uranus_bigtts', "Lola", "通用场景、教学场景"],
  ['pt_female_bv173narrator_uranus_bigtts', "Emma", "视频配音、客服场景"],
  ['pt_female_bv530_uranus_bigtts', "Sofia", "通用场景、视频配音"],
  ['pt_male_bv531_uranus_bigtts', "Arthur", "通用场景、教学场景"],
  ['pt_female_mari_uranus_bigtts', "Mari", "教学场景、视频配音"],
  ['pt_male_martins_uranus_bigtts', "Toby", "通用场景、教学场景"],
  ['pt_male_rael_uranus_bigtts', "Rael", "教学场景、视频配音"],
  ['ru_female_af07_uranus_bigtts', "Amelia", "有声阅读、视频配音"],
  ['ru_female_irinae_uranus_bigtts', "Irinae", "有声阅读、视频配音"],
  ['ru_male_pavel_uranus_bigtts', "Pavel", "通用场景、视频配音"],
  ['ru_female_sophie_uranus_bigtts', "Ksenia", "通用场景"],
  ['ru_male_vlad_uranus_bigtts', "Silas", ""],
  ['th_female_bv568_angry_uranus_bigtts', "Valeria", "教学场景、视频配音"],
  ['th_female_bv568_fear_uranus_bigtts', "Iris", "有声阅读、视频配音"],
  ['th_female_bv568_happy_uranus_bigtts', "Zara", "通用场景、视频配音"],
  ['th_female_bv568_hate_uranus_bigtts', "Valentina", "通用场景、视频配音"],
  ['th_female_bv568_neutral_uranus_bigtts', "Mildred", "通用场景、视频配音"],
  ['th_female_bv568_sad_uranus_bigtts', "Lydia", "视频配音、客服场景"],
  ['th_female_bv568_suprise_uranus_bigtts', "Phoebe", "有声阅读、视频配音"],
  ['tl_female_annika_uranus_bigtts', "Annika", "通用场景、视频配音"],
  ['tl_male_ed_uranus_bigtts', "Ed", "通用场景、视频配音"],
  ['tl_female_hervie_uranus_bigtts', "Hervie", "有声阅读、视频配音"],
  ['vi_female_hong_uranus_bigtts', "Hong", "通用场景、客服场景"],
  ['vi_female_ling_uranus_bigtts', "Ling", "通用场景、视频配音"],
  ['vi_female_linh_uranus_bigtts', "Linh", "视频配音"],
  ['vi_female_partner_uranus_bigtts', "Partner", "视频配音、客服场景"],
  ['vi_female_ruan_uranus_bigtts', "Ruan", "通用场景、有声阅读"],
  ['vi_female_wu_uranus_bigtts', "Wu", "通用场景、视频配音"],
  ['vi_male_wumg_uranus_bigtts', "Wumg", "通用场景、客服场景"],
  ['it_male_enzo_uranus_bigtts', "Enzo", "通用场景、教学场景"],
];

// ID 开头那一段是语言。大多数就是通用的语言代码，下面几个是火山自己的写法。
const LANGUAGE_OF: Record<string, string> = { mx: 'es', tl: 'fil' };

// 整理成页面要的样子。名字写成「名字 - 场景」，页面会把后半截当附注。这些音色没有试听的地址。
export const doubaoVoices = () =>
  DOUBAO_VOICES.map(([id, name, use]) => {
    const [lang, gender] = id.split('_');
    return { id, name: use ? `${name} - ${use}` : name, gender: gender === 'female' || gender === 'male' ? gender : '', language: LANGUAGE_OF[lang] || lang, accent: '', previewUrl: '' };
  });
